services:
  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - '${APP_PORT:-3001}:${APP_PORT:-3001}'
      - '${ADMIN_PORT:-3002}:${ADMIN_PORT:-3002}'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_MANAGEMENT_URL: http://rabbitmq:15672
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASS:-guest}@rabbitmq:5672
    env_file:
      - ../.env
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d database']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

volumes:
  redis_data:
  rabbitmq_data:
  postgres_data:


networks:
  backend:
    driver: bridge
